name: Server

defaults:
  run:
    shell: bash
    working-directory: src/apps/server

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'package.json'
      - 'src/apps/server/**'
      - '.github/workflows/server.yml'
  pull_request:
    branches: [main]
    paths:
      - 'package.json'
      - 'src/apps/server/**'
      - '.github/workflows/server.yml'

jobs:
  docker:
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./src/apps/server/Dockerfile
          target: runner
          builder: ${{ steps.buildx.outputs.name }}
          tags: repro-server:latest
          cache-from: type=gha, scope=${{ github.workflow }}
          cache-to: type=gha, scope=${{ github.workflow }},mode=max
